language: ruby
bundler_args: --without development

rvm:
  - 2.0
  - 2.2
  - jruby-1.7
  - jruby-9.0.0.0

# Make Travis use JRuby 9K GA
before_install:
  - 'if [[ "$TRAVIS_RUBY_VERSION" =~ "jruby-9.0.0.0" ]]; then rvm get head && rvm reload && rvm use --install $TRAVIS_RUBY_VERSION; fi'
